### ISSUE TITLE
EquipmentProperties and Entrance: Rename `door` to `doors`

### ISSUE THREAD

**Issue by k00ni** [sozialhelden/a11yjson#13]
There can be equipment, which has more than 1 door, for instance elevators. EquipmentProperties.`door` should therefore be renamed to `doors`.

The same goes for `Entrance`, there are places which have multiple doors in the entrance area.

This change would be in line with [Entrance.stairs](https://sozialhelden.github.io/ac-format/interfaces/entrance.html#stairs).

**Comment by opyh** [comment]
I agree!

**Comment by opyh** [comment]
Revision: I changed my mind: want to get nearer to schema.org, which uses singular form for most things, so I'll keep the singular form for now.
