### ISSUE TITLE
Add `unlockableFromTheOutside` attribute to `Door`

### ISSUE THREAD

**Issue by k00ni** [sozialhelden/a11yjson#19]
I would like to add the following properties to `Door`:

| Property                                         | Data Type |
|:-------------------------------------------------|:----------|
| unlockableFromTheOutside              | boolean      |

**Side notes:**
* **unlockableFromTheOutside** - That information is important for toilet doors. For safety reasons some doors are unlockable from the outside.

**Comment by opyh** [comment]
Are there use cases where this info is relevant for toilet users (not facility managers)?

**Comment by opyh** [comment]
(Reopen if you want) :)

**Comment by k00ni** [comment]
> Are there use cases where this info is relevant for toilet users (not facility managers)?

If I remember correctly, some toilet doors allow unlocking from outside. I was told that it is a security feature to help a person who can't leave because of an accident for instance. I can ask again, if that is not enough.
