### ISSUE TITLE
Information about car rental stations like from teilauto?

### ISSUE THREAD

**Issue by k00ni** [sozialhelden/a11yjson#21]
What do you think about extending the specification with information about car rental stations? Which properties might be of interest?

### Motivation

One might want to know if the station is reachable or if there are notable obstacles, like holes or threshold on the way. For me its not about rental stations with cars for people with disabilities. Its about people who might want to know, for instance, if their grandparents with rollator can reach the station resp. cars.

### Random thoughts

* Main entity should be `Parking`. 
* Because stations are mostly with cars not suitable for wheelchair users, `WheelchairParking` could be ignored here IMHO.
* When starts the station? So here pathways around the station of interest? What radius makes sense?
* **The following questions should be answered:**
  1. Has the station a door i have to use? (e.g. door width, door height, automatic or not,..)
  2. Has the area obstacles, like holes in the ground, which might hinder you?
  3. How accessible are the ways to the station, like from the next main street or TRAM station?

What do you think?

**Comment by opyh** [comment]
I think this is a complex structure that OSM is good at already - we could simply use data from there.
