### ISSUE TITLE
Is there a process to propose / discuss changes/additions to the specification?

### ISSUE THREAD

**Issue by k00ni** [sozialhelden/a11yjson#4]
I would like to be compatible to your specification with my own data, but there are differences in modelling, which have to be bridged. So before going into detail, is there a process to propose / discuss changes/additions to the specification?

Thanks.

**Comment by mutaphysis** [comment]
Right now we don't have a process set up - so far they were all just discussion within sozialhelden & framefield.

But we would love to see outside contributions & discussions on a11y-json! 

I would say that we start with using github issues for this. Feel free to create one or more issues for the fields that could be improved or that are completely missing. Pull Requests with the proposed changes would also very welcome, they could be merged once we have an agreement. 

Once I am back working actively on the project I will also start in converting the remaining TODOs from earlier reviews into issues. We probably should add some documentation for the semantic versioning and the code style, but this can come later.

It will be best to keep at least @opyh & maybe @holgerd in the loop on this.

Hope this helps,
Henrik

**Comment by mutaphysis** [comment]
@holgerd , @opyh maybe you already discussed this, but it might be time to start formalizing the process of improving a11y-json.

**Comment by k00ni** [comment]
Alright, thanks for the info @mutaphysis.

**Comment by k00ni** [comment]
I hope i didn't spammed you too much these days. 

Porting my current data model to a11y-json was very interesting. You chose an approach to model different entities and combine them. My approach was to have only a `Place` and it has ALL information, separated with a basic prefix like `ramp_` or `elevator_`. This is because of the project history.

It would be great, if you could answer the following questions:
1. Is there a paper or something which describes the "why's" behind your decisions when creating this specification?
2. Is there a process to validate given data in your service, like wheelmap or accessibility.cloud? Or do "trust" the person/organization, which uploads them. As i understand it, everybody can participate and provide information about places, for instance.

**Comment by opyh** [comment]
Thanks for your input. We've already have a good amount of real-life talk but to answer these questions publicly:

1. No. I'd love to write one and be on more conferences but lack time currently. Anybody can write one, and we’re open to suggestions from papers! If this is about better documentation: I'm all up for adding more in-depth explanations in the JSDoc comments and for a healthy amount of transparent discussion on GitHub. Some of the attributes are semantically not well-defined yet, but first we need to let this project lift off :) The repo allows using [semver](https://semver.org), and I imagine we could add migration scripts for automatically upgrading data when bigger/more datasets exist.
2. On Wheelmap, we rely on users to trust the listed source. Of course, a community-driven process yields different quality than what a staff of professional surveyors would collect. We have both kind of data on the platforms. We will feature data sources more prominently in the near future to make more clear what users can expect from a rating. I think this is something where the schema.org infrastructure will come in handy at some point.

[1] To be frank, I have my issues with Academia’s processes. I see value in basing standards on the academic process and peer reviews, but the main target audience of A11yJSON is app developers. GitHub PRs + Issues are the most transparent peer review process you can get. And the academic process itself is less accessible. Some examples:

- Linking PDF content in hypertext is cumbersome and PDFs are meant to be printed, not for screens
- Responses papers often end up behind paywalls
- The scientific community tends to intentionally using language as an exclusive code
- Source code + PRs + Issue discussions are a pretty transparent process, which is an ideal that the scientific community strives for, too
- Contrary to call for papers dates, GitHub has no deadline pressure. Anyone can open or respond to issues whenever they want! ;)

**Comment by opyh** [comment]
For an even more web-like, community-based process, we have founded the [Linked Data for Accessibility Community Group](https://www.w3.org/community/lda/). ‘Real’ work there is going to start soon.
