### ISSUE TITLE
What means "isAccessibleWithWheelchair"? And what is required to set it true?

### ISSUE THREAD

**Issue by k00ni** [sozialhelden/a11yjson#5]
What is required to rate something `isAccessibleWithWheelchair = true`? Are there any objective measures that must be given to rate something accessible with wheelchairs?

**Comment by opyh** [comment]
Of course there are varying international definitions and standards about the definition of 'wheelchair accessible'. We go with a pragmatic definition so far:

- the place/facility is accessible either 1) stepless or 2) via a ramp
- the main function of the place or facility is usable while using a wheelchair

In a similar way, 'partially wheelchair accessible' means:
- people accessing the place/facility need to take maximally one step with maximally 7cm height or a ramp
- the majority of functions of the place or facility are usable while using a wheelchair

We plan to simplify the attribute definition by using a string enum for this in the near future.

This attribute is just an interpretation of physical data. Interpretations are subjective and subject to change (e.g. who knows what wheelchairs will be capable of in the future?), so data sources should include original, measurable physical attributes to not lose this information.

**Comment by k00ni** [comment]
Thank you.

**Comment by k00ni** [comment]
Is there a property which reflects the fact that something is `partially wheelchair accessible`? Currently only `isAccessibleWithWheelchair` is available. Would you mind adding an additional property or would you model it differently?

**Comment by opyh** [comment]
Currently, we have [`partiallyAccessibleWith`](https://github.com/sozialhelden/ac-format/blob/master/src/Accessibility.ts#L29) for this. The attribute can be `true` and is exclusive with its counterpart in `accessibleWith`, so only one of them should be set at the same time.

Wheelmap's definition of 'limited'/'partial' accessibility differs a bit:
- it doesn't only include the entrance. For limited accessibility (marked in yellow) the place's main functions have to be fully accessible with a wheelchair.
- If there is one step at the entrance, it must not be higher than 7cm. If it is higher, the accessibility is 'not accessible'.
- Aisles have to be wide enough to turn.
- We only cover _if_ there is a ramp, but not its slope: If there is a ramp and the entrance is wide enough, we regard it as accessible.

Wheelmap has ~940k places that mostly were tagged with this definition. It currently is the biggest data source available in A11yJSON, and does not have the physical data that the rating is based on, so we cannot change these flags in the Wheelmap dataset ([which would have to be done in OpenStreetMap](https://wiki.openstreetmap.org/wiki/Key:wheelchair)).

No worries though, it is fine if you publish your source with your own, different definition of what you regard as (limited) accessibility :) If you include the data that this definition is based on, it's simple for each data consumer to apply their own rules if necessary. If we include the data on Wheelmap, we can show the details there, too.

**Comment by opyh** [comment]
In the near future, we plan to migrate these data to a single enum value (`true`/`false`/`'limited').
