### ISSUE TITLE
interface to import

### ISSUE THREAD

**Issue by posipa** [sozialhelden/a11yjson#75]
Hi, I want to use model but first I have to import interface to my database. How I can do that easily? A json format aside with table one would be great.

**Comment by opyh** [comment]
You can create table definitions from the SimpleSchema definitions automatically. There are various libraries to convert SimpleSchema to other schema formats. Database abstraction layers like Hasura or Prisma can create working apps from Schemas like this, and there are many smaller libraries that can create database definitions (for example as SQL) directly from schema information.

Closing this - I hope this answers your question, feel free to reopen if it doesn’t! 🙂
